service: up-bank-ynab-transformer
frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${opt:awsProfile}
  stage: prod
  region: us-east-1
  logRetentionInDays: 90
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

functions:
  upWebhookHandler:
    handler: src/index.upWebhook
    events:
      - http:
          path: webhook/up
          method: post
